//! Build a binary NVS partition image from a `provisioning.toml` and
//! (optionally) flash it to the device. See `provisioning-plan.md`.
//!
//! The actual NVS binary format is generated by ESP-IDF's
//! `nvs_partition_gen.py` (already on disk inside `.embuild/`). We just
//! produce the CSV input it expects, then shell out.

use anyhow::{anyhow, bail, Context, Result};
use clap::Parser;
use serde::Deserialize;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Parser)]
#[command(version, about = "Build + flash NVS partition image from provisioning.toml")]
struct Cli {
    /// Path to provisioning.toml.
    #[arg(long, default_value = "provisioning.toml")]
    config: PathBuf,

    /// Where to write the generated NVS .bin.
    #[arg(long, default_value = "target/nvs.bin")]
    out: PathBuf,

    /// NVS partition size in bytes. Must match `partitions.csv` (the `nvs`
    /// row's size column). Default matches the current 0x6000 (24 KB) NVS.
    #[arg(long, default_value_t = 0x6000)]
    nvs_size: u32,

    /// Offset in flash to write to. Must match `partitions.csv` nvs offset.
    #[arg(long, default_value = "0x9000")]
    nvs_offset: String,

    /// If true, also flash the generated image to the device via espflash.
    #[arg(long)]
    flash: bool,

    /// Serial port for flashing.
    #[arg(long, default_value = "/dev/cu.usbserial-0001")]
    port: String,

    /// Path to ESP-IDF's nvs_partition_gen.py. Defaults to the in-repo
    /// embuild copy that gets cloned by `make build`.
    #[arg(long, default_value = ".embuild/espressif/esp-idf/v5.2.2/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py")]
    nvs_gen: PathBuf,

    /// Path to the python interpreter to run nvs_partition_gen.py with.
    /// Defaults to the embuild-bootstrapped 3.12 venv (matches what the
    /// firmware build uses; ensures script deps are present).
    #[arg(long, default_value = ".embuild/espressif/python_env/idf5.2_py3.12_env/bin/python")]
    python: PathBuf,
}

#[derive(Deserialize, Debug)]
struct ProvisioningConfig {
    wifi: WifiConfig,
    trust: TrustConfig,
}

#[derive(Deserialize, Debug)]
struct WifiConfig {
    ssid: String,
    pass: String,
}

#[derive(Deserialize, Debug)]
struct TrustConfig {
    identities: Vec<TrustedIdentity>,
    fulcio_root_pem: PathBuf,
    fulcio_intermediate_pem: PathBuf,
}

#[derive(Deserialize, serde::Serialize, Debug)]
struct TrustedIdentity {
    identity: String,
    issuer: String,
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let args = Cli::parse();

    let toml_str = std::fs::read_to_string(&args.config)
        .with_context(|| format!("read {}", args.config.display()))?;
    let mut cfg: ProvisioningConfig =
        toml::from_str(&toml_str).context("parse provisioning.toml")?;

    // Resolve PEM paths relative to the directory of provisioning.toml,
    // so the user can write `fulcio_root_pem = "trust/fulcio_root.pem"`
    // and it works regardless of where the tool is invoked from.
    let config_dir = args
        .config
        .canonicalize()
        .with_context(|| format!("canonicalize {}", args.config.display()))?
        .parent()
        .ok_or_else(|| anyhow!("no parent dir for {}", args.config.display()))?
        .to_path_buf();
    if cfg.trust.fulcio_root_pem.is_relative() {
        cfg.trust.fulcio_root_pem = config_dir.join(&cfg.trust.fulcio_root_pem);
    }
    if cfg.trust.fulcio_intermediate_pem.is_relative() {
        cfg.trust.fulcio_intermediate_pem =
            config_dir.join(&cfg.trust.fulcio_intermediate_pem);
    }

    tracing::info!(
        identities = cfg.trust.identities.len(),
        ssid = cfg.wifi.ssid,
        "loaded provisioning config",
    );

    if !args.nvs_gen.exists() {
        bail!(
            "{} not found — run `make build` once so embuild clones ESP-IDF",
            args.nvs_gen.display()
        );
    }

    // Stage the trust/identities JSON to a temp file (nvs_partition_gen
    // reads `binary` values from disk, not stdin).
    let target_dir = args
        .out
        .parent()
        .unwrap_or_else(|| Path::new("target"))
        .to_path_buf();
    std::fs::create_dir_all(&target_dir)
        .with_context(|| format!("create {}", target_dir.display()))?;
    let identities_json_path = target_dir.join("nvs-identities.json");
    let identities_json =
        serde_json::to_vec(&cfg.trust.identities).context("serialize identities")?;
    std::fs::write(&identities_json_path, &identities_json)
        .with_context(|| format!("write {}", identities_json_path.display()))?;
    tracing::info!(
        path = %identities_json_path.display(),
        bytes = identities_json.len(),
        "wrote identities JSON",
    );

    // Build the NVS CSV.
    let csv_path = target_dir.join("nvs.csv");
    write_csv(
        &csv_path,
        &cfg,
        &identities_json_path,
    )
    .context("write NVS CSV")?;
    tracing::info!(path = %csv_path.display(), "wrote NVS CSV");

    // Run nvs_partition_gen.py.
    let status = Command::new(&args.python)
        .arg(&args.nvs_gen)
        .arg("generate")
        .arg(&csv_path)
        .arg(&args.out)
        .arg(args.nvs_size.to_string())
        .status()
        .with_context(|| format!("run {}", args.nvs_gen.display()))?;
    if !status.success() {
        bail!("nvs_partition_gen.py failed: {}", status);
    }
    let bin_size = std::fs::metadata(&args.out)?.len();
    tracing::info!(
        path = %args.out.display(),
        bytes = bin_size,
        "generated NVS partition image",
    );

    if args.flash {
        tracing::info!(
            port = %args.port,
            offset = %args.nvs_offset,
            "flashing NVS image",
        );
        let status = Command::new("espflash")
            .args([
                "write-bin",
                "--port",
                &args.port,
                &args.nvs_offset,
                args.out.to_str().context("non-utf8 out path")?,
            ])
            .status()
            .context("run espflash write-bin")?;
        if !status.success() {
            bail!("espflash write-bin failed: {}", status);
        }
        tracing::info!("NVS partition flashed; reboot the device to pick it up");
    } else {
        tracing::info!(
            "build complete; pass --flash to write to the device, or run `make provision`",
        );
    }

    Ok(())
}

fn write_csv(
    path: &Path,
    cfg: &ProvisioningConfig,
    identities_path: &Path,
) -> Result<()> {
    let mut wtr = csv::WriterBuilder::new()
        .quote_style(csv::QuoteStyle::Necessary)
        .from_path(path)?;
    // Header
    wtr.write_record(&["key", "type", "encoding", "value"])?;

    // wifi namespace
    wtr.write_record(&["wifi", "namespace", "", ""])?;
    wtr.write_record(&["ssid", "data", "string", &cfg.wifi.ssid])?;
    wtr.write_record(&["pass", "data", "string", &cfg.wifi.pass])?;

    // trust namespace
    wtr.write_record(&["trust", "namespace", "", ""])?;
    wtr.write_record(&[
        "identities",
        "file",
        "binary",
        identities_path
            .to_str()
            .ok_or_else(|| anyhow!("identities path not UTF-8"))?,
    ])?;
    wtr.write_record(&[
        "fulcio_root",
        "file",
        "binary",
        cfg.trust
            .fulcio_root_pem
            .to_str()
            .ok_or_else(|| anyhow!("fulcio_root_pem path not UTF-8"))?,
    ])?;
    wtr.write_record(&[
        "fulcio_inter",
        "file",
        "binary",
        cfg.trust
            .fulcio_intermediate_pem
            .to_str()
            .ok_or_else(|| anyhow!("fulcio_intermediate_pem path not UTF-8"))?,
    ])?;

    wtr.flush()?;
    Ok(())
}
